<h2>Cadastrar categoria</h2>

<?php
	$form = $this->form;

	$this->formElementErrors()
		 ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
		 ->setMessageCloseString('</div>')
		 ->render($form);

	$form->setAttribute('action', $this->url('categoria/default', array('controller' => 'categoria', 'action' => 'inserir')));
	
	$form->prepare();

	echo $this->form()->openTag($form);

	echo $this->formCollection($form);

	echo $this->form()->closeTag();
?>